### PR TITLE
Added BASE API Models

### PR DESCRIPTION
**Pull request by Prahitha**
Added the base app in settings.py and models for API and API Variant in models.py of base app

### CODE REVIEW

**Comment by masterashu** [comment]
You might have to wait for #4 to be merged since a custom User model must have the first migration.

**Comment by adwait-thattey** [comment]
Your tests are failing. Please look into it

**Comment by adwait-thattey** [comment]
@Prahitha The concerned PR has been merged. Please make the migrations 
Also before doing that, you will need to rebase your branch. If you have questions regarding rebasing, please let me know

**Comment by adwait-thattey** [comment]
Looks Good. Thanks

**Comment by adwait-thattey** [comment]
Squashing and merging

**Pull request merged**
